### PR TITLE
return values of magic methods, part 2

### PR DESCRIPTION
**Pull request by aleswita**
**ftp_alloc** - Returns TRUE on success or FALSE on failure.
**ftp_cdup** - Returns TRUE on success or FALSE on failure.
**ftp_chdir** - Returns TRUE on success or FALSE on failure. If changing directory fails, PHP will also throw a warning.
**ftp_chmod** - Returns the new file permissions on success or FALSE on error.
**ftp_close** - Returns TRUE on success or FALSE on failure.
**ftp_delete** - Returns TRUE on success or FALSE on failure.
**ftp_exec** - Returns TRUE if the command was successful (server sent response code: 200); otherwise returns FALSE.
**ftp_get** - Returns TRUE on success or FALSE on failure.
**ftp_login** - Returns TRUE on success or FALSE on failure. If login fails, PHP will also throw a warning.
**ftp_mkdir** - Returns the newly created directory name on success or FALSE on error.
**ftp_nlist** - Returns an array of filenames from the specified directory on success or FALSE on error.
**ftp_pasv** - Returns TRUE on success or FALSE on failure.
**ftp_put** - Returns TRUE on success or FALSE on failure.
**ftp_pwd** - Returns the current directory name or FALSE on error.
**ftp_rawlist** - Returns an array where each element corresponds to one line of text. Returns FALSE when passed directory is invalid.
**ftp_rename** - Returns TRUE on success or FALSE on failure. Upon failure (such as attempting to rename a non-existent file), an E_WARNING error will be emitted.
**ftp_rmdir** - Returns TRUE on success or FALSE on failure.
**ftp_site** - Returns TRUE on success or FALSE on failure.
**ftp_systype** - Returns the remote system type, or FALSE on error.

+ plus added virtual method for **ftp_append** and **ftp_mlsd**

### CODE REVIEW

**Comment by dg** [comment]
In the case of error they throw FtpException, so “void” is correct

**Comment by aleswita** [comment]
In PR: https://github.com/dg/ftp-php/pull/10 we are talking about ftp_put, but this func return only bool without throws.

But change return value of **chDir**, **login**, **rename** and **setOption**  to **void**

**Comment by aleswita** [comment]
@dg need something more?

I need these for PHPStan analysis, because using some FTP function like bellow
```php
if ($ftp->fGet($temp, 'picture.jpeg', FTP_BINARY, 0)) {
	...
}
```
and PHPStan (PHPStorm too) show error "Result of method Ftp::fGet() (void) is used."

**Comment by dg** [comment]
Mně se to nechce řešit :-) Udělej si fork.

**Pull request closed without merging**
